#!/bin/sh

BRANCH_NAME=$(git branch --show-current)

# grep 실패 시에도 exit 0 유지
JIRA_TICKET=$(echo "$BRANCH_NAME" | grep -o '[A-Z]\+-[0-9]\+' || true)

COMMIT_MSG_FILE=$1

# 티켓 번호가 있고, 이미 포함 안 돼 있을 때만 추가
if [ -n "$JIRA_TICKET" ] && ! grep -q "\[$JIRA_TICKET\]" "$COMMIT_MSG_FILE"; then
  sed -i "" "1s/^/\[$JIRA_TICKET\] /" "$COMMIT_MSG_FILE"
fi
